services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ab-youtube-dev
    volumes:
      - ab-youtube-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ab-youtube-redis:/data
    ports:
      - "6379:6379"
    env_file:
      - .env

volumes:
  ab-youtube-redis:
  ab-youtube-mysql:
