services:
  web:
    build:
      context: .
      dockerfile: ./DockerFile.dev
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
      - /app/node_modules
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ab-youtube-dev
    volumes:
      - ab-youtube-mysql:/var/lib/mysql
  redis:
    image: redis:latest
    volumes:
      - ab-youtube-redis:/data

volumes:
  ab-youtube-redis:
  ab-youtube-mysql:
